# Generated by Django 3.2.4 on 2023-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
